version: '3'

services:
  teste:
    container_name: 'teste_db'
    image: postgres:14.5
    restart: always
    ports:
      - '9996:5432'
    volumes:
      - ./postgres_dev/data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env.postgres
